BEGIN TRY

BEGIN TRAN;

DROP TABLE IF EXISTS [jwk_private_key];

CREATE TABLE [jwk_private_key]
(
  [id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [encrypted_private_key_pem] NVARCHAR(max) NOT NULL,
  [base64_iv] NVARCHAR(64) NOT NULL,
  [validate_at] DATETIME NOT NULL,
  [expire_at] DATETIME NOT NULL,
  [closed_at] DATETIME NOT NULL,
  [created_at] DATETIME NOT NULL DEFAULT GETUTCDATE(),
  CONSTRAINT [pk_private_key] PRIMARY KEY ([id]),
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
  ROLLBACK TRAN;
END;
THROW

END CATCH
