services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sample-sqlserver
    ports:
      - 1433:1433
    env_file:
      - .env
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/secrets:/var/opt/mssql/sec