name: Bugfix
description: 不具合修正用テンプレート
title: "[Bug]: "
labels: ["draft"]
type: "Bug"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 発生している事象
      value: |
        - xxxx
    validations:
      required: true
  - type: textarea
    id: step
    attributes:
      label: 再現手順
      description: 再現手順が判明している場合は記載
      value: |
        1. xxxx
    validations:
      required: false
  - type: textarea
    id: plan
    attributes:
      label: 修正方針
      description: 方針が決定している場合は記載
      value: |
        - xxxx
    validations:
      required: false