name: Feature development
description: 機能開発用テンプレート
title: "[Feature]: "
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: 実装の説明
      description: このIssueによって実現予定である機能について詳細に記述すること
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足
      value: |
        - xxxx
    validations:
      required: false