BEGIN TRY

BEGIN TRAN;

CREATE TABLE [oauth_client]
(
  [id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [name] NVARCHAR(20),
  [secret] NVARCHAR(MAX) NOT NULL,
  [redirect_uris] NVARCHAR(MAX) NOT NULL,
  [scopes] NVARCHAR(MAX) NOT NULL,
  [created_at] DATETIME NOT NULL DEFAULT GETUTCDATE(),
  [modified_at] DATETIME NOT NULL DEFAULT GETUTCDATE(),
  CONSTRAINT [pk_oauth_client] PRIMARY KEY ([id]),
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
  ROLLBACK TRAN;
END;
THROW

END CATCH
