/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPrivateRouteImport } from './routes/_auth/private'
import { Route as AuthOauth2AuthorizeRouteImport } from './routes/_auth/oauth2/authorize'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPrivateRoute = AuthPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOauth2AuthorizeRoute = AuthOauth2AuthorizeRouteImport.update({
  id: '/oauth2/authorize',
  path: '/oauth2/authorize',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/private': typeof AuthPrivateRoute
  '/oauth2/authorize': typeof AuthOauth2AuthorizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/private': typeof AuthPrivateRoute
  '/oauth2/authorize': typeof AuthOauth2AuthorizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/private': typeof AuthPrivateRoute
  '/_auth/oauth2/authorize': typeof AuthOauth2AuthorizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/private' | '/oauth2/authorize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/private' | '/oauth2/authorize'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/private'
    | '/_auth/oauth2/authorize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/private': {
      id: '/_auth/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof AuthPrivateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/oauth2/authorize': {
      id: '/_auth/oauth2/authorize'
      path: '/oauth2/authorize'
      fullPath: '/oauth2/authorize'
      preLoaderRoute: typeof AuthOauth2AuthorizeRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthPrivateRoute: typeof AuthPrivateRoute
  AuthOauth2AuthorizeRoute: typeof AuthOauth2AuthorizeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPrivateRoute: AuthPrivateRoute,
  AuthOauth2AuthorizeRoute: AuthOauth2AuthorizeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
