name: api - lint and test

on:
  workflow_call:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies
        working-directory: ./apps/api
        run: bun install --frozen-lockfile

      - name: Lint
        working-directory: ./apps/api
        run: bun run lint

      - name: Generate Prisma Client
        working-directory: ./apps/api
        run: bun run prisma#generate

      - name: Test
        working-directory: ./apps/api
        run: bun run test
