name: api - test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
    paths:
      - 'apps/api/**'
      - '.github/workflows/api_test.yml'
      - '.github/workflows/api_lint_test.yml'

jobs:
  lint-and-test:
    uses: ./.github/workflows/api_lint_test.yml
