name: api test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
    paths:
      - 'apps/api/**'
      - '.github/workflows/api_test.yml'
      - '.github/workflows/call_api_lint.yml'
      - '.github/workflows/call_api_test.yml'

jobs:
  lint:
    uses: ./.github/workflows/call_api_lint.yml

  test:
    uses: ./.github/workflows/call_api_test.yml
