name: backend deploy - staging

on:
  push:
    branches:
      - staging
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend_deploy_staging.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - staging
  # 手動トリガーを許可
  workflow_dispatch:

concurrency:
  group: backend-deploy-staging-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    uses: ./.github/workflows/call_backend_lint.yml

  test:
    uses: ./.github/workflows/call_backend_test.yml

  build:
    needs: [lint, test]
    uses: ./.github/workflows/call_backend_build.yml
    with:
      environment: 'staging'
      registry_domain: 'connectsamplestgjecr01.azurecr.io'
      repository_name: 'connect-sample-backend-01'
      tag: 'latest'
      dockerfile_path: './apps/backend/Dockerfile'
      context_path: './apps/backend'
    secrets: inherit

  deploy:
    # PRの場合はdeployをスキップ
    if: github.event_name != 'pull_request'
    needs: build
    uses: ./.github/workflows/call_backend_deploy.yml
    with:
      environment: 'staging'
      container_app_name: 'connect-sample-stg-je-api-01'
      resource_group: 'connect-sample-stg-je'
      registry_domain: 'connectsamplestgjecr01.azurecr.io'
      repository_name: 'connect-sample-backend-01'
      tag: 'latest'
    secrets: inherit