name: call frontend build

on:
  workflow_call:
    inputs:
      environment:
        description: '環境名'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies
        working-directory: ./apps/frontend
        run: bun install --frozen-lockfile

      - name: Build
        working-directory: ./apps/frontend
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$VARS_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env
          bun run build
          cp ../../staticwebapp.config.json ./dist

      - name: Upload Publish Files
        uses: actions/upload-artifact@v4
        with:
          name: publish-files
          path: ./apps/frontend/dist