name: call frontend deploy

on:
  workflow_call:
    inputs:
      environment:
        description: '環境名'
        required: true
        type: string
    secrets:
      AZURE_STATIC_WEB_APPS_DEPLOY_TOKEN:
        description: 'Azure Static Web Apps デプロイ用トークン'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download Publish Files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: publish-files
          path: dist

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@4d27395796ac319302594769cfe812bd207490b1 # v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/dist'
          # `build_job`を個別に定義している為、デフォルトのビルドステップを使用しない
          skip_app_build: true
