name: call backend build

on:
  workflow_call:
    inputs:
      environment:
        description: '環境名'
        required: true
        type: string
      registry_domain:
        description: 'コンテナレジストリ'
        required: true
        type: string
      repository_name:
        description: 'コンテナリポジトリ名'
        required: true
        type: string
      tag:
        description: 'コンテナイメージのタグ'
        required: true
        type: string
      dockerfile_path:
        description: 'Dockerfileのパス'
        required: true
        type: string
      context_path:
        description: 'ビルドコンテキストのパス'
        required: true
        type: string
    secrets:
      CONTAINER_REGISTRY_USERNAME:
        description: 'コンテナレジストリのユーザー名'
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: 'コンテナレジストリのパスワード'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ inputs.registry_domain }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          tags: ${{ inputs.registry_domain }}/${{ inputs.repository_name }}:${{ inputs.tag }}
          file: ${{ inputs.dockerfile_path }}
          context: ${{ inputs.context_path }}
          build-args: |
            ENV_NAME=${{ inputs.environment }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
