name: call frontend test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies
        working-directory: ./apps/frontend
        run: bun install --frozen-lockfile

      - name: Test
        working-directory: ./apps/frontend
        run: bun run test