name: Dependabot Security Alert

on:
  schedule:
    # リポジトリでの Dependabot アラート生成タイミングに合わせる
    - cron: "10 22 * * 0-4" # 平日 7:10 JST

  # テスト用
  workflow_dispatch:

permissions:
  contents: read

jobs:
  notify:
    uses: upward-inc/org-workflows/.github/workflows/dependabot-security-alert.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MAIN_CHANNEL_WEBHOOK_URL }}
      UPWARD_SHARED_WORKFLOWS_APP_ID: ${{ vars.UPWARD_SHARED_WORKFLOWS_APP_ID }}
      UPWARD_SHARED_WORKFLOWS_APP_PRIVATE_KEY: ${{ secrets.UPWARD_SHARED_WORKFLOWS_APP_PRIVATE_KEY }}
    with:
      severity: ${{ vars.DEPENDABOT_ALERT_SEVERITY }}
      mentions: ${{ vars.DEPENDABOT_ALERT_MENTIONS }}