name: frontend deploy - staging

on:
  push:
    branches:
      - staging
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend_deploy_staging.yml'
      - '.github/workflows/call_frontend_*.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - staging
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend_deploy_staging.yml'
      - '.github/workflows/call_frontend_*.yml'
  # 手動トリガーを許可
  workflow_dispatch:

concurrency:
  group: frontend-deploy-staging-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/call_frontend_lint.yml

  test:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/call_frontend_test.yml

  build:
    if: github.event.action != 'closed'
    needs: [lint, test]
    uses: ./.github/workflows/call_frontend_build.yml
    with:
      environment: 'staging'
    secrets: inherit

  deploy:
    # PRの場合はdeployをスキップ
    if: github.event_name != 'pull_request'
    needs: build
    uses: ./.github/workflows/call_frontend_deploy.yml
    with:
      environment: 'staging'
    secrets: inherit

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/call_frontend_close_pull_request.yml
    with:
      environment: 'staging'
    secrets: inherit
